source 'https://github.com/18638597928/TestSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

target 'PersonInfo_Example' do
  pod 'PersonInfo', :path => '../'

  target 'PersonInfo_Tests' do
    inherit! :search_paths

    
  end
end
